config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :sessions, :only=>[:new, :create, :destroy]

  root "pages#home"
  get '/contact', to: "pages#contact"
   
  
  get '/about', to: "pages#about"
  get '/help', to: "pages#help"

  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :post

  get "/signup", to: "users#new"

  

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	email_regex = /\A[\w+.]+@[a-z\.]+\.[a-z]+\z/i
	validates :name,  :presence => true,
					  :length   => {:maximum =>50}
	validates :email, :presence => true,
					  :format   => {:with=>email_regex},
					  :uniqueness => {:case_sensitive => false}

	validates :password, :presence=>true,
						 :confirmation=>true,
						 :length=>{:within=> 6..40}

	before_save :encrypt_password

	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

	class << self
		def authenticate(email, submitted_password)
			user = find_by_email(email)
			return nil if user.nil?
			return user if user.has_password?(submitted_password)
		end
	end
	private
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
		end

		def encrypt(string)
			secure_hash("#{salt}--#{string}")       # this is not the final implementation!
		end

		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end

		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  	@title = "Home"
  end

  def contact
  	@title = "Contact"
  end
  def about
  	@title = "About"
  end
  def help
  	@title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@title = "Sign In"
  end

  def create
  	#  in params session will be like this
  	# {:session => { :email=> "", :passsword => "" }}

    user = User.authenticate(params[:session][:email],
  						 params[:session][:password])
    if user.nil?
    	flash.now[:error] = "Invalid email/password combination"
    	# flash.now, it means remain only in current request, if new request is made even it is first request after error, remove flash

    	@title = "Sign In"
    	render "new"
    else
    	sign_in user
    	redirect_to user
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  end
  
  def new
  	@title = "Sign up"
  	@user = User.new
  end

  def create
  	# raise will raise an exceptional runtime error, use for debugging
  	# raise params[:user].inspect

  	@user = User.new(strong_parameters(params[:user]))
  	if @user.save
      # flash[:success] = "Welcome to Turtle tweets"
      # redirect_to user_path(@user)
      
      # we can also refactor above two lines in this way

      redirect_to @user, flash: {:success=>"Welcome to Turtle tweets"}
    else
      @title = "Sign Up"
      render 'new'
    end
  end

  private

    def strong_parameters(user)
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Return a title on a per-page basis
	def title
      base_title = "Ruby on Rails Tutorial Turtle Tweets"
      if @title.nil?
         base_title
      else
         "#{base_title} | #{@title}"
      end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {:size=>50})
		gravatar_image_tag(user.email.downcase, :alt=>"#{user.name}",
									   :class=>"gravatar",
									   :gravatar => options)
	end
end

app/views/layouts/_footers.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", "http://news.railstutorial.org/" %></li>
			<li><%= link_to "Rails Tutorials", "http://railstutorial.org/" %></li>
		</ul>
	</nav>
</footer>	

app/views/layouts/_headers.html.erb
<header>
 	<%= link_to image_tag("tweet_logo.jpg", alt: "Sample App",  :class=>"round", :size => '60x60'), 
				root_path  
 	%>
 	<nav class="round">
 		<ul>
 			<li><%= link_to "Home", root_path %></li>
 			<li><%= link_to "Help", help_path %></li>
 			<li><%= link_to "Sign in", signin_path %></li>
 		</ul>
 	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'blueprint/ie'%>
<!--[if lt IE 8]<%= stylesheet_link_tag 'blueprint/ie'%><![endif]-->
<%= stylesheet_link_tag 'custom', :media=>"screen"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= render "layouts/stylesheets"%>
</head>
<body>
	 <div class="container">
		 <%= render "layouts/headers"%>
		 <section class="round">
		 <% flash.each do |key, value|%>
		 	 <div class="flash <%=key%>"><%= value %></div>
		 <% end %>
			 <%= yield %>
		 </section>
	 	 <%= render :partial=>"layouts/footers"%>
	 	 <%= debug params if Rails.env.development?%>
	 </div>      
</body>
</html>

app/views/pages/about.html.erb
<h1>Turtle Tweets About Us</h1>
  <p>
     <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> is a project to make a book and screencasts to teach web development with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This is the sample application for the tutorial.
  </p>



app/views/pages/contact.html.erb
<h1>Turtle Tweets Contact</h1>
 <p>
     Contact Ruby on Rails Tutorial about the sample app at <a href="http://railstutorial.org/feedback">feedback page</a>
 </p>

app/views/pages/help.html.erb
<h1>Turtle Tweets Help</h1>
 <p>
     You can get help on Ruby on Rails Tutorial at <a href="http://railstutorial.org/help">Rails Tutorial help page</a>
 </p>

app/views/pages/home.html.erb
<h1>Turtle Tweets</h1>
  <p>
     This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
  </p>
<%= link_to "Sign up now!", new_user_path, :class=> "signup_button round"%>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any?%>
  <div id="error_explanation">
  	<h2>
  		<%= pluralize(@user.errors.count, "error") %>
  		prohibited this user from being saved
  	</h2>
  	<div id="error_msgs">
	  	<p>There were problems with the following fields:</p>
	  	<ul>
		  	<% @user.errors.full_messages.each do |message|%>
		  		<li><%= message %></li>
		  	<% end %>
	  	</ul>
  	</div>
  </div>

<%end%>  

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f|%>
	<%= render 'shared/error_messages'%>
	<div class='field'>
		<%= f.label :name%><br />
		<%= f.text_field :name%>
	</div>

	<div class='field'>
		<%= f.label :email%><br />
		<%= f.text_field :email%>
	</div>

	<div class='field'>
		<%= f.label :password%><br />
		<%= f.password_field :password%>
	</div>

	<div class='field'>
		<%= f.label :password_confirmation, "Confirmation"%><br />
		<%= f.password_field :password_confirmation%>
	</div>

	<div class='action'>
		<%= f.submit "Sign Up"%><br />
	</div>
<%end%>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class='main'>
			<h3>
				<%=gravatar_for @user%>
				<%= @user.name%>

			</h3>
		</td>
		<td class='sidebar round'>
			<strong>Name:</strong> <%=@user.name%><br />
			<strong>URL:</strong> <small><%=link_to user_url(@user), @user%></small><br />
		</td>
	</tr>

</table>